from __future__ import annotations

FLORA_SPECIES = {'quercus_alba': {'id': 'quercus_alba',
                  'common_name': 'White oak',
                  'scientific_name': 'Quercus alba',
                  'kind': 'tree',
                  'biomes': ['temperate-forest'],
                  'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                  'stage_threshold': 26,
                  'base_growth': 1.0,
                  'spread_stage_index': 3,
                  'spread_radius': 3,
                  'spread_chance': 0.035,
                  'spread_cooldown': 22,
                  'temp_min': -8,
                  'temp_max': 30,
                  'dry_penalty': 1,
                  'season_mod': {'spring': 1.3, 'summer': 1.15, 'autumn': 0.75, 'winter': 0.28},
                  'weather_mod': {'clear': 1.0, 'rain': 1.12, 'storm': 0.92, 'dry': 0.7, 'fog': 0.95}},
 'betula_papyrifera': {'id': 'betula_papyrifera',
                       'common_name': 'Paper birch',
                       'scientific_name': 'Betula papyrifera',
                       'kind': 'tree',
                       'biomes': ['temperate-forest'],
                       'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                       'stage_threshold': 22,
                       'base_growth': 1.15,
                       'spread_stage_index': 2,
                       'spread_radius': 3,
                       'spread_chance': 0.05,
                       'spread_cooldown': 18,
                       'temp_min': -12,
                       'temp_max': 29,
                       'dry_penalty': 2,
                       'season_mod': {'spring': 1.4, 'summer': 1.2, 'autumn': 0.8, 'winter': 0.24},
                       'weather_mod': {'clear': 1.0, 'rain': 1.18, 'storm': 0.94, 'dry': 0.6, 'fog': 1.0}},
 'vaccinium_corymbosum': {'id': 'vaccinium_corymbosum',
                          'common_name': 'Highbush blueberry',
                          'scientific_name': 'Vaccinium corymbosum',
                          'kind': 'plant',
                          'biomes': ['temperate-forest', 'river-lowlands'],
                          'stages': ['sprout', 'juvenile', 'mature', 'flowering', 'seeded'],
                          'stage_threshold': 16,
                          'base_growth': 1.35,
                          'spread_stage_index': 3,
                          'spread_radius': 2,
                          'spread_chance': 0.07,
                          'spread_cooldown': 14,
                          'temp_min': -4,
                          'temp_max': 31,
                          'dry_penalty': 2,
                          'season_mod': {'spring': 1.5, 'summer': 1.25, 'autumn': 0.95, 'winter': 0.18},
                          'weather_mod': {'clear': 1.0, 'rain': 1.22, 'storm': 0.85, 'dry': 0.62, 'fog': 0.97}},
 'allium_canadense': {'id': 'allium_canadense',
                      'common_name': 'Wild onion',
                      'scientific_name': 'Allium canadense',
                      'kind': 'plant',
                      'biomes': ['temperate-forest', 'river-lowlands', 'highland-heath'],
                      'stages': ['sprout', 'juvenile', 'mature', 'flowering', 'seeded'],
                      'stage_threshold': 14,
                      'base_growth': 1.45,
                      'spread_stage_index': 2,
                      'spread_radius': 2,
                      'spread_chance': 0.08,
                      'spread_cooldown': 12,
                      'temp_min': -6,
                      'temp_max': 32,
                      'dry_penalty': 1,
                      'season_mod': {'spring': 1.55, 'summer': 1.1, 'autumn': 0.82, 'winter': 0.2},
                      'weather_mod': {'clear': 1.0, 'rain': 1.16, 'storm': 0.9, 'dry': 0.72, 'fog': 1.0}},
 'picea_mariana': {'id': 'picea_mariana',
                   'common_name': 'Black spruce',
                   'scientific_name': 'Picea mariana',
                   'kind': 'tree',
                   'biomes': ['taiga'],
                   'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                   'stage_threshold': 27,
                   'base_growth': 0.9,
                   'spread_stage_index': 3,
                   'spread_radius': 2,
                   'spread_chance': 0.03,
                   'spread_cooldown': 24,
                   'temp_min': -22,
                   'temp_max': 24,
                   'dry_penalty': 2,
                   'season_mod': {'spring': 1.1, 'summer': 1.0, 'autumn': 0.72, 'winter': 0.38},
                   'weather_mod': {'clear': 1.0, 'rain': 1.08, 'storm': 0.9, 'dry': 0.7, 'fog': 1.02}},
 'pinus_sylvestris': {'id': 'pinus_sylvestris',
                      'common_name': 'Scots pine',
                      'scientific_name': 'Pinus sylvestris',
                      'kind': 'tree',
                      'biomes': ['taiga', 'highland-heath'],
                      'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                      'stage_threshold': 24,
                      'base_growth': 1.0,
                      'spread_stage_index': 3,
                      'spread_radius': 3,
                      'spread_chance': 0.04,
                      'spread_cooldown': 20,
                      'temp_min': -18,
                      'temp_max': 27,
                      'dry_penalty': 1,
                      'season_mod': {'spring': 1.2, 'summer': 1.1, 'autumn': 0.8, 'winter': 0.36},
                      'weather_mod': {'clear': 1.0, 'rain': 1.08, 'storm': 0.92, 'dry': 0.75, 'fog': 1.0}},
 'cladonia_rangiferina': {'id': 'cladonia_rangiferina',
                          'common_name': 'Reindeer lichen',
                          'scientific_name': 'Cladonia rangiferina',
                          'kind': 'plant',
                          'biomes': ['taiga', 'alpine'],
                          'stages': ['sprout', 'juvenile', 'mature', 'seeded', 'withered'],
                          'stage_threshold': 20,
                          'base_growth': 0.78,
                          'spread_stage_index': 2,
                          'spread_radius': 1,
                          'spread_chance': 0.05,
                          'spread_cooldown': 16,
                          'temp_min': -26,
                          'temp_max': 20,
                          'dry_penalty': 0,
                          'season_mod': {'spring': 1.05, 'summer': 1.0, 'autumn': 0.88, 'winter': 0.65},
                          'weather_mod': {'clear': 1.0, 'rain': 1.0, 'storm': 0.95, 'dry': 0.92, 'fog': 1.1}},
 'pteridium_aquilinum': {'id': 'pteridium_aquilinum',
                         'common_name': 'Bracken fern',
                         'scientific_name': 'Pteridium aquilinum',
                         'kind': 'plant',
                         'biomes': ['taiga', 'temperate-forest'],
                         'stages': ['sprout', 'juvenile', 'mature', 'flowering', 'withered'],
                         'stage_threshold': 15,
                         'base_growth': 1.2,
                         'spread_stage_index': 2,
                         'spread_radius': 2,
                         'spread_chance': 0.055,
                         'spread_cooldown': 13,
                         'temp_min': -10,
                         'temp_max': 28,
                         'dry_penalty': 2,
                         'season_mod': {'spring': 1.45, 'summer': 1.22, 'autumn': 0.72, 'winter': 0.18},
                         'weather_mod': {'clear': 1.0, 'rain': 1.2, 'storm': 0.9, 'dry': 0.62, 'fog': 1.04}},
 'artemisia_tridentata': {'id': 'artemisia_tridentata',
                          'common_name': 'Big sagebrush',
                          'scientific_name': 'Artemisia tridentata',
                          'kind': 'plant',
                          'biomes': ['arid-steppe'],
                          'stages': ['sprout', 'juvenile', 'mature', 'seeded', 'withered'],
                          'stage_threshold': 19,
                          'base_growth': 0.95,
                          'spread_stage_index': 2,
                          'spread_radius': 2,
                          'spread_chance': 0.045,
                          'spread_cooldown': 15,
                          'temp_min': -8,
                          'temp_max': 35,
                          'dry_penalty': 0,
                          'season_mod': {'spring': 1.2, 'summer': 1.0, 'autumn': 0.9, 'winter': 0.4},
                          'weather_mod': {'clear': 1.0, 'rain': 1.08, 'storm': 0.95, 'dry': 0.95, 'fog': 0.92}},
 'bouteloua_gracilis': {'id': 'bouteloua_gracilis',
                        'common_name': 'Blue grama',
                        'scientific_name': 'Bouteloua gracilis',
                        'kind': 'plant',
                        'biomes': ['arid-steppe', 'highland-heath'],
                        'stages': ['sprout', 'juvenile', 'mature', 'seeded', 'withered'],
                        'stage_threshold': 13,
                        'base_growth': 1.15,
                        'spread_stage_index': 2,
                        'spread_radius': 2,
                        'spread_chance': 0.09,
                        'spread_cooldown': 10,
                        'temp_min': -6,
                        'temp_max': 36,
                        'dry_penalty': 1,
                        'season_mod': {'spring': 1.35, 'summer': 1.25, 'autumn': 0.86, 'winter': 0.25},
                        'weather_mod': {'clear': 1.0, 'rain': 1.35, 'storm': 1.05, 'dry': 0.78, 'fog': 0.95}},
 'opuntia_humifusa': {'id': 'opuntia_humifusa',
                      'common_name': 'Prickly pear',
                      'scientific_name': 'Opuntia humifusa',
                      'kind': 'plant',
                      'biomes': ['arid-steppe'],
                      'stages': ['sprout', 'juvenile', 'mature', 'flowering', 'seeded'],
                      'stage_threshold': 20,
                      'base_growth': 0.88,
                      'spread_stage_index': 3,
                      'spread_radius': 1,
                      'spread_chance': 0.03,
                      'spread_cooldown': 18,
                      'temp_min': -4,
                      'temp_max': 38,
                      'dry_penalty': 0,
                      'season_mod': {'spring': 1.0, 'summer': 1.15, 'autumn': 0.85, 'winter': 0.3},
                      'weather_mod': {'clear': 1.0, 'rain': 1.05, 'storm': 0.9, 'dry': 1.0, 'fog': 0.85}},
 'vachellia_tortilis': {'id': 'vachellia_tortilis',
                        'common_name': 'Acacia',
                        'scientific_name': 'Vachellia tortilis',
                        'kind': 'tree',
                        'biomes': ['arid-steppe'],
                        'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                        'stage_threshold': 25,
                        'base_growth': 0.82,
                        'spread_stage_index': 3,
                        'spread_radius': 2,
                        'spread_chance': 0.028,
                        'spread_cooldown': 25,
                        'temp_min': -2,
                        'temp_max': 39,
                        'dry_penalty': 0,
                        'season_mod': {'spring': 1.0, 'summer': 1.1, 'autumn': 0.86, 'winter': 0.32},
                        'weather_mod': {'clear': 1.0, 'rain': 1.15, 'storm': 1.0, 'dry': 0.95, 'fog': 0.82}},
 'pinus_mugo': {'id': 'pinus_mugo',
                'common_name': 'Dwarf mountain pine',
                'scientific_name': 'Pinus mugo',
                'kind': 'tree',
                'biomes': ['alpine', 'highland-heath'],
                'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                'stage_threshold': 26,
                'base_growth': 0.85,
                'spread_stage_index': 3,
                'spread_radius': 2,
                'spread_chance': 0.03,
                'spread_cooldown': 22,
                'temp_min': -20,
                'temp_max': 22,
                'dry_penalty': 1,
                'season_mod': {'spring': 1.05, 'summer': 1.0, 'autumn': 0.85, 'winter': 0.45},
                'weather_mod': {'clear': 1.0, 'rain': 1.05, 'storm': 0.9, 'dry': 0.8, 'fog': 1.02}},
 'myosotis_alpestris': {'id': 'myosotis_alpestris',
                        'common_name': 'Alpine forget-me-not',
                        'scientific_name': 'Myosotis alpestris',
                        'kind': 'plant',
                        'biomes': ['alpine', 'highland-heath'],
                        'stages': ['sprout', 'juvenile', 'mature', 'flowering', 'seeded'],
                        'stage_threshold': 15,
                        'base_growth': 1.05,
                        'spread_stage_index': 3,
                        'spread_radius': 1,
                        'spread_chance': 0.06,
                        'spread_cooldown': 13,
                        'temp_min': -16,
                        'temp_max': 19,
                        'dry_penalty': 2,
                        'season_mod': {'spring': 1.3, 'summer': 1.1, 'autumn': 0.72, 'winter': 0.22},
                        'weather_mod': {'clear': 1.0, 'rain': 1.1, 'storm': 0.82, 'dry': 0.6, 'fog': 1.05}},
 'leontopodium_nivale': {'id': 'leontopodium_nivale',
                         'common_name': 'Edelweiss',
                         'scientific_name': 'Leontopodium nivale',
                         'kind': 'plant',
                         'biomes': ['alpine'],
                         'stages': ['sprout', 'juvenile', 'mature', 'flowering', 'withered'],
                         'stage_threshold': 18,
                         'base_growth': 0.86,
                         'spread_stage_index': 2,
                         'spread_radius': 1,
                         'spread_chance': 0.036,
                         'spread_cooldown': 16,
                         'temp_min': -18,
                         'temp_max': 17,
                         'dry_penalty': 1,
                         'season_mod': {'spring': 1.2, 'summer': 1.0, 'autumn': 0.75, 'winter': 0.32},
                         'weather_mod': {'clear': 1.0, 'rain': 1.08, 'storm': 0.82, 'dry': 0.74, 'fog': 1.0}},
 'sphagnum_spp': {'id': 'sphagnum_spp',
                  'common_name': 'Sphagnum moss',
                  'scientific_name': 'Sphagnum spp.',
                  'kind': 'plant',
                  'biomes': ['alpine', 'river-lowlands', 'taiga'],
                  'stages': ['sprout', 'juvenile', 'mature', 'seeded', 'withered'],
                  'stage_threshold': 17,
                  'base_growth': 1.1,
                  'spread_stage_index': 2,
                  'spread_radius': 1,
                  'spread_chance': 0.072,
                  'spread_cooldown': 12,
                  'temp_min': -14,
                  'temp_max': 24,
                  'dry_penalty': 3,
                  'season_mod': {'spring': 1.3, 'summer': 1.1, 'autumn': 0.9, 'winter': 0.34},
                  'weather_mod': {'clear': 1.0, 'rain': 1.28, 'storm': 1.08, 'dry': 0.5, 'fog': 1.12}},
 'salix_nigra': {'id': 'salix_nigra',
                 'common_name': 'Black willow',
                 'scientific_name': 'Salix nigra',
                 'kind': 'tree',
                 'biomes': ['river-lowlands'],
                 'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                 'stage_threshold': 21,
                 'base_growth': 1.22,
                 'spread_stage_index': 2,
                 'spread_radius': 3,
                 'spread_chance': 0.065,
                 'spread_cooldown': 16,
                 'temp_min': -8,
                 'temp_max': 31,
                 'dry_penalty': 3,
                 'season_mod': {'spring': 1.5, 'summer': 1.25, 'autumn': 0.9, 'winter': 0.22},
                 'weather_mod': {'clear': 1.0, 'rain': 1.33, 'storm': 1.05, 'dry': 0.48, 'fog': 1.08}},
 'populus_deltoides': {'id': 'populus_deltoides',
                       'common_name': 'Eastern cottonwood',
                       'scientific_name': 'Populus deltoides',
                       'kind': 'tree',
                       'biomes': ['river-lowlands'],
                       'stages': ['seedling', 'sapling', 'young', 'mature', 'ancient'],
                       'stage_threshold': 20,
                       'base_growth': 1.28,
                       'spread_stage_index': 2,
                       'spread_radius': 3,
                       'spread_chance': 0.07,
                       'spread_cooldown': 15,
                       'temp_min': -7,
                       'temp_max': 32,
                       'dry_penalty': 3,
                       'season_mod': {'spring': 1.52, 'summer': 1.3, 'autumn': 0.9, 'winter': 0.2},
                       'weather_mod': {'clear': 1.0, 'rain': 1.35, 'storm': 1.0, 'dry': 0.45, 'fog': 1.05}},
 'phragmites_australis': {'id': 'phragmites_australis',
                          'common_name': 'Common reed',
                          'scientific_name': 'Phragmites australis',
                          'kind': 'plant',
                          'biomes': ['river-lowlands'],
                          'stages': ['sprout', 'juvenile', 'mature', 'flowering', 'seeded'],
                          'stage_threshold': 12,
                          'base_growth': 1.35,
                          'spread_stage_index': 2,
                          'spread_radius': 2,
                          'spread_chance': 0.1,
                          'spread_cooldown': 9,
                          'temp_min': -5,
                          'temp_max': 33,
                          'dry_penalty': 4,
                          'season_mod': {'spring': 1.5, 'summer': 1.32, 'autumn': 0.9, 'winter': 0.16},
                          'weather_mod': {'clear': 1.0, 'rain': 1.4, 'storm': 1.15, 'dry': 0.4, 'fog': 1.1}},
 'typha_latifolia': {'id': 'typha_latifolia',
                     'common_name': 'Cattail',
                     'scientific_name': 'Typha latifolia',
                     'kind': 'plant',
                     'biomes': ['river-lowlands'],
                     'stages': ['sprout', 'juvenile', 'mature', 'seeded', 'withered'],
                     'stage_threshold': 13,
                     'base_growth': 1.3,
                     'spread_stage_index': 2,
                     'spread_radius': 2,
                     'spread_chance': 0.085,
                     'spread_cooldown': 10,
                     'temp_min': -6,
                     'temp_max': 31,
                     'dry_penalty': 4,
                     'season_mod': {'spring': 1.45, 'summer': 1.25, 'autumn': 0.9, 'winter': 0.18},
                     'weather_mod': {'clear': 1.0, 'rain': 1.32, 'storm': 1.12, 'dry': 0.42, 'fog': 1.08}}}
